# Generated by Django 6.0.6 on 2026-07-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Compras_APP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudcompra",
            name="justificacion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="solicitudcompra",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
