# Generated by Django 6.0.6 on 2026-07-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras_APP', '0003_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Compras_APP.cotizacion')),
            ],
        ),
    ]
