# Generated by Django 6.0.6 on 2026-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Compras_APP", "0004_ordencompra"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("ruc", models.CharField(max_length=13, unique=True)),
                ("telefono", models.CharField(blank=True, default="", max_length=20)),
                ("correo", models.EmailField(blank=True, default="", max_length=254)),
            ],
        ),
    ]
